CC = g++
CCFLAGS = -Wall -g

assignment6: assignment6.cc
	$(CC) $(CCFLAGS) assignment5.cc assignment6.cc assignment6main.cc -o assignment6.exe

run:
	./assignment6.exe > assignment6.out

clean:
	-rm assignment6.exe
